### ISSUE TITLE
Container-based deployment

### ISSUE THREAD

**Issue by brucellino** [apel/apel#149]
Hi APEL devs.

I'm working on the redeployment of the regional APEL server for @AAROC. By default, I'm writing the deployment with AnsibleContainer. I'd like to know if anyone has considered the deployment of the regional accounting server in a container-based environment - it will probably be deployed to an OpenShift instance. 

The topology is basically two linked containers (see https://github.com/AAROC/AAROC.apel-regional-server), one `from: mysql:5.7` to contain the database server, but with a data volume for the data itself, and the other `from: centos:7` to act as the APEL server. The host certificate and key of course will be kept in a secure data container mounted by the apel service at deploy time, or encrypted with oc or k8s secrets. 

The main issue I need to deal with is the long-running processes in the APEL container. As far as I can tell these are cron jobs ? Is there a reference somewhere to tell me what jobs need to be enabled, or is this entirely taken care of by [@apel/ssm](https://github.com/apel/ssm) ?

**Comment by gregcorbett** [comment]
[This](https://github.com/apel/rest/blob/dev/yaml/ansible.yml#L23) might be useful to look at. As part of a different project we looked into deploying the APEL server as a docker container using `docker-compose` and `ansible`. That project focused on cloud accounting, so sadly you can't just deploy the existing container but it gives you a reference point for how to go about it. 

The ansible deployment focused on deploying containers on a single host, so we just used directories for persistent storage rather than data containers. 

You'll need to have service files so the loader can be started and stopped like a service, and a cron job to periodically stop the loader / start the summariser. You'll also need configuration files for the APEL db, loader and summariser. We can provide examples of these files via email.

We also found the need to mount this [configuration file](https://github.com/apel/rest/blob/dev/docker/etc/mysql/conf.d/51_comp.cnf) into the database container, as mysql5.6 was stricter on type checking.

Does that help?

**Comment by brucellino** [comment]
Thanks @gregcorbett, that playbook from Indigo helps ! I would propose to re-work it a bit though, because there is some opacity in how the images are built. Using Ansible Container, I'm writing an [Ansible role](https://galaxy.ansible.com/AAROC/AAROC_regional-apel-server/) which can be re-used to build and deploy services. It's a bit clearer, I think. It's also easier to deploy to different platforms (the playbooks are generated on the fly for Docker, k8s, OC). 
I'd be happy to send PR if that's what you guys are in to... 

(also, seems that the `indigodatacloud/apel` repo is private or b0rked ? : 
```
docker search apel
... 
indigodatacloud/apel                    A repo to allow a docker image to be built f…   0                                       [OK]
docker pull indigodatacloud/apel
Using default tag: latest
Error response from daemon: manifest for indigodatacloud/apel:latest not found
```

> You'll need to have service files so the loader can be started and stopped like a service, 
> and a cron job to periodically stop the loader / start the summariser. You'll also need 
> configuration files for the APEL db, loader and summariser. We can provide examples of 
> these files via email.
Ok - this was the main issue I was having. You're confirming that there needs to be a systemd or initd system to have things run like daemons ? 
But the main thing is still : **what processes and services need to be invoked** ? As far as I can tell, it's : 

  - mysqld (provided by 
  - various crons for summariser/loader/unloader/sender
  - ??? we good ? 

If that's the case, it sounds like I need two linked  containers (mysql:5.6 + apel), which which is the sql daemon, the other which runs `crond`. right ? 

>  You'll also need configuration files for the APEL db, loader and summariser. 
Thanks ! I got the mail - this will help. I'm using [templates](https://github.com/AAROC/AAROC.regional-apel-server/tree/master/templates/etc/apel) and [role variables](https://github.com/AAROC/AAROC.regional-apel-server/blob/master/defaults/main.yml). For the sensitive vars (passwords, private keys), we will use environment variables and secrets, to follow [12 factor](https://www.12factor.net/). 

Thanks a mil ! 
Bruce

**Comment by brucellino** [comment]
edit : guess it helps to read mails. I got  the service config. Thanks !  I would like to spend a bit of time implementing this, before I close the issue. The next issue will be related to sending test messages.

**Comment by gregcorbett** [comment]
No worries, with regards to the `indigodatacloud/apel` docker repository, you have to specify a tag. And the only tag is `indigodatacloud/apel:1.6.0-1`

**Comment by brucellino** [comment]
> And the only tag is indigodatacloud/apel:1.6.0-1
Now I just feel dumb. Sorry, should have spotted that.
