### ISSUE TITLE
Dbloader crashes when StAR has incorrect number of fields

### ISSUE THREAD

**Issue by stuartpullinger** [apel/apel#93]
DBloader crashes when StAR record does not contain correct number of fields.

The database function to load storage records accepts 18 parameters [1]. If we receive a StAR record with fewer than the 18 parameters that we need, the dbloader crashes with the message below [2].

To fix this, we could add fields to the list of mandatory fields in the storage record object [3] or create default values in the Storage Record object __init__ method [4].

[1] https://github.com/apel/apel/blob/dev/schemas/storage.sql#L224
[2]
```
2016-01-13 10:02:15,531 - loader - INFO - Loading message 00000482/569546f527eea2. ID = 00062110/5630fa670b8687
2016-01-13 10:02:15,531 - loader - INFO - Loading message from /C=UK/O=eScience/OU=CLRC/L=RAL/CN=heplnx203.pp.rl.ac.uk
2016-01-13 10:02:15,557 - loader - INFO - Message contains 12 records
2016-01-13 10:02:15,714 - dbloader - ERROR - Unexpected exception. Traceback follows...
Traceback (most recent call last):
  File "/usr/bin/apeldbloader", line 117, in run_as_daemon
    loader.load_all_msgs()
  File "/usr/lib/python2.4/site-packages/apel/db/loader/loader.py", line 149, in load_all_msgs
    self.load_msg(msg_text, signer)
  File "/usr/lib/python2.4/site-packages/apel/db/loader/loader.py", line 199, in load_msg
    self._apeldb.load_records(records, source=signer)
  File "/usr/lib/python2.4/site-packages/apel/db/backends/mysql.py", line 152, in load_records
    c.execute(proc, values)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 159, in execute
TypeError: not enough arguments for format string
2016-01-13 10:02:15,722 - dbloader - INFO - The loader will shutdown.
2016-01-13 10:02:15,722 - loader - INFO - The loader has shut down.
2016-01-13 10:02:15,722 - dbloader - INFO - =======================
```
[3] https://github.com/apel/apel/blob/dev/apel/db/records/storage.py#L35

**Comment by jcgordon** [comment]
Recently (january) rejected records contain all mandatory fields plus Site  and RecordIdentity/Group.

Last October we received records which ended up in our database with most fields with values (many but not all None). Either they were sending different records or we were processing them differently.

**Comment by jcgordon** [comment]
I found the old records which were accepted in October 2015. When I compare them with the January ones I see one big difference. Some but not all of the new records have an extra tag  
<sr:GroupAttribute sr:attributeType='role'>production</sr:GroupAttribute>

I assume the original test data was only a subset or that this is a new user role added after the tests. I suspect the former as the number of VOs shouldn’t have changed in so short a time. 

parseStarRecord line 140 onwards looks like it is attempting to parse GroupAttributes. I cannot tell how successful it is.

Storage.py line 40 doesn’t mention the attributes or anything that looks like it might be them. 

StarRecords in storage database on acctest doesn’t have them either.

mysql>  describe StarRecords;
+---------------------------+--------------+------+-----+---------+-------+
| Field                     | Type         | Null | Key | Default | Extra |
+---------------------------+--------------+------+-----+---------+-------+
| RecordId                  | varchar(255) | NO   | PRI | NULL    |       |
| CreateTime                | datetime     | NO   |     | NULL    |       |
| StorageSystemID           | int(11)      | NO   | MUL | NULL    |       |
| SiteID                    | int(11)      | NO   |     | NULL    |       |
| StorageShareID            | int(11)      | NO   | MUL | NULL    |       |
| StorageMediaID            | int(11)      | NO   | MUL | NULL    |       |
| StorageClassID            | int(11)      | NO   | MUL | NULL    |       |
| FileCount                 | int(11)      | YES  |     | NULL    |       |
| DirectoryPath             | varchar(255) | YES  |     | NULL    |       |
| LocalUser                 | varchar(255) | YES  |     | NULL    |       |
| LocalGroup                | varchar(255) | YES  |     | NULL    |       |
| UserIdentityID            | int(11)      | NO   | MUL | NULL    |       |
| GroupID                   | int(11)      | NO   | MUL | NULL    |       |
| StartTime                 | datetime     | NO   |     | NULL    |       |
| EndTime                   | datetime     | NO   |     | NULL    |       |
| ResourceCapacityUsed      | bigint(20)   | NO   |     | NULL    |       |
| LogicalCapacityUsed       | bigint(20)   | YES  |     | NULL    |       |
| ResourceCapacityAllocated | bigint(20)   | YES  |     | NULL    |       |
+---------------------------+--------------+------+-----+---------+-------+
18 rows in set (0.00 sec)

So, I suggest that the loader is barfing because it finds fields it doesn’t expect, not because it doesn’t have enough.Need to check the apel.db object for the loading. 

I did notice though that even the old messages which were accepted don’t always have the same number of tags. E.g <sr:StorageMedia>disk</sr:StorageMedia> is present in one record and missing in the other two. So, we have no problem with some tags being missing. Of course this doesn’t mean that the parser doesn’t create null values to load into the database. When it is not present this field has the value None in the database. It looks like the extra ones that cause the problem. 

Does this sound feasible. Can anyone confirm?

**Comment by jcgordon** [comment]
Here is an example of a tag in a message which is rejected but is not present in messages which are accepted: 

<sr:GroupAttribute sr:attributeType='role'>production</sr:GroupAttribute>

We need to extend the database schema to include role and group attirbutes and the loader to accept them.

**Comment by tofu-rocketry** [comment]
You were mostly on the right lines there. It is handling the `sr:GroupAttribute` elements a special case:

1. The `star_parser` parses the XML file and picks out the individual records.
1. It looks for the elements it wants to put into the DB.
1. It reads the `sr:GroupAttribute` element **separately**.
1. It outputs a list that contains `StorageRecord` objects, **and** `GroupAttributeRecord` objects **if** they were present in the previous record.

The database handling part of the code is then meant to understand that this is a different type of record and load it differently, but what actually happens is that it assumes that all records in the list are of the same type.

So, it reads and loads the first `StorageRecord` fine, but then it'll eventually get to a `GroupAttributeRecord` and try to load it as a `StorageRecord`, which fails!  :disappointed:

Definitely not what I was expecting. I need a stiff drink, but tea will have to do.  :coffee:

**Comment by tofu-rocketry** [comment]
So the UR-2.0 and Storage Record spec are pretty much the same for group attributes and both support multiple entries. However, only the Storage spec gives examples for role and authority – both have an example for subgroup.

I've also compared the fields in the storage record to CPU job records and that's helped convince me that two extra columns for subgroup and role wouldn't be excessive.

However, I'm going to keep the extra table for any group attributes that aren't "subgroup" or "role". After we add summaries, we could leave processing any attributes that end up in that table (i.e. that aren't subgroup or role) to the portal, in case sites want to do something crazy with it.

I think that's the best solution I can come up with that both simplifies summarising, but also means we can support the specs as written and not remove functionality.

Additionally, as there’s no requirement at the moment for extra group attributes other than subgroup or role, we can put a warning in the log but still load the record if someone sends us data that has an unexpected group attribute.

**Comment by jcgordon** [comment]
That sounds good. I asked the ogf group if anyone remembered what authority was about. No one replied positively yet.

John

On 7 Sep 2016 6:05 p.m., Adrian <notifications@github.com> wrote:

So the UR-2.0 and Storage Record spec are pretty much the same for group attributes and both support multiple entries. However, only the Storage spec gives examples for role and authority – both have an example for subgroup.

I've also compared the fields in the storage record to CPU job records and that's helped convince me that two extra columns for subgroup and role wouldn't be excessive.

However, I'm going to keep the extra table for any group attributes that aren't "subgroup" or "role". After we add summaries, we could leave processing any attributes that end up in that table (i.e. that aren't subgroup or role) to the portal, in case sites want to do something crazy with it.

I think that's the best solution I can come up with that both simplifies summarising, but also means we can support the specs as written and not remove functionality.

Additionally, as there’s no requirement at the moment for extra group attributes other than subgroup or role, we can put a warning in the log but still load the record if someone sends us data that has an unexpected group attribute.
